services:
  db:
    image: postgres:16
    container_name: postgres-dev
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1243"
      POSTGRES_DB: database
      TZ: America/Buenos_Aires
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: