spring.application.name=e-comerce
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5433/database
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=1243

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Configuracion de SMTP (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ammatiendaa123@gmail.com
spring.mail.password=tmybzjxdytctsltg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# Clave secreta encriptada en Base64 (No la compartas con nadie)
jwt.secret=RXN0YUVzVW5hQ2xhdmVTZWNyZXRhUGFyYUFtbWFFY29tbWVyY2UyMDI2IQ==
# Tiempo de expiracion del token (86400000 ms = 24 horas)
jwt.expiration=86400000

mercadopago.access-token=TEST-8617147806910517-091800-4088d2b4bbf3b522288b45e2730ccd71-3699660760