spring.application.name=e-comerce
server.port=8080

spring.datasource.url=${DB_URL}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Configuracion de SMTP (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# Clave secreta encriptada en Base64 (No la compartas con nadie)
jwt.secret=${JWT_SECRET}
# Tiempo de expiracion del token (86400000 ms = 24 horas)
jwt.expiration=86400000
tienda.costo-envio=2500
mercadopago.access-token=${MP_TOKEN}
app.frontend-url=http://localhost:5173

mercadopago.notification-url=

spring.config.import=optional:file:.env[.properties]
